import { GroupView } from 'ng2-qgrid/core/group/group.view';
import { FilterView } from 'ng2-qgrid/core/filter/filter.view';
import { PivotView } from 'ng2-qgrid/core/pivot/pivot.view';
import { SortView } from 'ng2-qgrid/core/sort/sort.view';
import { PaginationView } from 'ng2-qgrid/core/pagination/pagination.view';
import { ColumnView } from 'ng2-qgrid/core/column/column.view';
import { HeadView } from 'ng2-qgrid/core/head/head.view';
import { BodyView } from 'ng2-qgrid/core/body/body.view';
import { FootView } from 'ng2-qgrid/core/foot/foot.view';
import { LayoutView } from 'ng2-qgrid/core/layout/layout.view';
import { SelectionView } from 'ng2-qgrid/core/selection/selection.view';
import { HighlightView } from 'ng2-qgrid/core/highlight/highlight.view';
import { EditView } from 'ng2-qgrid/core/edit/edit.view';
import { NavigationView } from 'ng2-qgrid/core/navigation/navigation.view';
import { ScrollView } from 'ng2-qgrid/core/scroll/scroll.view';
import { StyleView } from 'ng2-qgrid/core/style/style.view';
import { RowDetailsView } from 'ng2-qgrid/core/row-details/row.details.view';
import { RootService } from 'ng2-qgrid/infrastructure/component';
import { GridService } from 'ng2-qgrid/main/grid';
import { VScrollService } from 'ng2-qgrid/main/core/scroll';
export declare class ViewCoreService {
    private root;
    private gridServiceFactory;
    private vscroll;
    destroy: any;
    group: GroupView;
    filter: FilterView;
    pivot: PivotView;
    sort: SortView;
    pagination: PaginationView;
    columns: ColumnView;
    head: HeadView;
    body: BodyView;
    foot: FootView;
    layout: LayoutView;
    selection: SelectionView;
    highlight: HighlightView;
    edit: EditView;
    nav: NavigationView;
    scroll: ScrollView;
    style: StyleView;
    rowDetails: RowDetailsView;
    constructor(root: RootService, gridServiceFactory: GridService, vscroll: VScrollService);
    init(): void;
}
